artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/RohitPawar001/datasets/raw/refs/heads/main/loan_dataset/archive%20(1).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/loan_approval_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir : artifacts/data_transformation
  data_file_path : artifacts/data_ingestion/loan_approval_dataset.csv
  

model_trainer:
  root_dir: artifacts/model_trainer
  x_train_data_path : artifacts/data_transformation/x_train.csv
  y_train_data_path : artifacts/data_transformation/y_train.csv
  model_name : model.joblib


model_evaluation:
  root_dir : artifacts/model_evaluation
  x_test_data_path : artifacts/data_transformation/x_test.csv
  y_test_data_path : artifacts/data_transformation/y_test.csv
  model_path : artifacts/model_trainer/model.joblib
  metric_file_name : artifacts/model_evaluation/model_metrics.json
