artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/RohitPawar001/datasets/raw/refs/heads/main/loan_dataset/archive%20(1).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/loan_approval_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt